name: anime_themes_player
description: A Music Player App which specifically plays Anime Themes
publish_to: 'none' 
version: 0.7.30+6
environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  get_storage: ^2.0.3
  fancy_bottom_navigation_2: ^0.3.5
  flutter_native_splash: ^2.1.6
  just_audio: ^0.9.37
  just_audio_background: ^0.0.1-beta.11
  cached_network_image: ^3.3.0
  audio_session: ^0.1.6+1
  http: ^0.13.4
  tap_to_expand: ^0.0.1
  qr_code_vision: ^0.1.0
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  implicitly_animated_reorderable_list_2: ^0.5.1
  flutter_meedu_videoplayer: ^4.3.1
 # media_kit_libs_android_video: ^1.0.3           # Android package for video native libraries.
 # media_kit_libs_ios_video: ^1.0.4         # iOS package for video (& audio) native libraries.
  video_player_web_hls: ^1.0.0+3
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  icons_launcher: ^1.1.7
flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  fonts:
    - family: ptsans
      fonts:
        - asset: lib/assets/ptsans.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_icons:
  image_path: 'lib/assets/at_comm_icon.png'
  ios: true
  android: true
  windows: true
  linux: true
  macos: true
  web: true
flutter_native_splash:
   color: "#fefefe"
   image: lib/assets/at_comm_icon.png