name: anime_themes_player
description: A Music Player App which specifically plays Anime Themes
publish_to: 'none' 
version: 0.5.20+1
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  get_storage: ^2.0.3
  fancy_bottom_navigation: ^0.3.3
  flutter_native_splash: ^2.1.6
  just_audio: ^0.9.21
  just_audio_libwinmedia: ^0.0.4
  just_audio_background: ^0.0.1-beta.5
  audio_session: ^0.1.6+1
  http: ^0.13.4
  tap_to_expand: ^0.0.1
  qr_code_vision: ^0.1.0
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  file_picker: ^4.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  icons_launcher: ^1.1.7
flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  fonts:
    - family: ptsans
      fonts:
        - asset: lib/assets/ptsans.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_icons:
  image_path: 'lib/assets/at_comm_icon.png'
  ios: true
  android: true
  windows: true
  linux: true
  macos: true
  web: true
flutter_native_splash:
   color: "#fefefe"
   image: lib/assets/at_comm_icon.png