name: anime_themes_player
description: A Music Player App which specifically plays Anime Themes
publish_to: 'none' 
version: 0.9.19+8
environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  get_storage: ^2.0.3
  flutter_snake_navigationbar: ^0.6.1
  flutter_native_splash: ^2.1.6
  url_launcher: ^6.3.1
  just_audio: ^0.9.40
  just_audio_background: ^0.0.1-beta.13
  cached_network_image: ^3.3.0
  package_info: ^2.0.0
  intl: ^0.17.0
  float_column: ^2.1.8
  implicitly_animated_reorderable_list_2: ^0.6.0
  media_kit: ^1.1.11                             # Primary package.
  media_kit_video: ^1.2.5                        # For video rendering.
  media_kit_libs_video: ^1.0.4                   # Native video dependencies.

dependency_overrides:
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  icons_launcher: ^2.1.7
flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  fonts:
    - family: ptsans
      fonts:
        - asset: lib/assets/ptsans.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_icons:
  image_path: 'lib/assets/at_comm_icon.png'
  ios: true
  android: true
  windows: true
  linux: true
  macos: true
  web: true
flutter_native_splash:
   color: "#fefefe"
   image: lib/assets/at_comm_icon.png